version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - $(aws ecr get-login-password --region us-west-2)
      - $(docker login --username AWS --password-stdin 618253162746.dkr.ecr.us-west-2.amazonaws.com)
