version: 0.2

phases:
  pre_build:
    commands:
      - echo Login into AWS ECR
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 618253162746.dkr.ecr.us-west-2.amazonaws.com
      - echo Installing Docker...
      - sudo apt-get update -y
      - sudo apt-get install -y docker.io
      - sudo service docker start
  build:
    commands:
      - echo Building Docker image...
      - sudo service docker start
      - sudo docker build .
  post_build:
    commands:
      - echo Pushing Docker image to ECR repository...
      - docker push 618253162746.dkr.ecr.us-west-2.amazonaws.com/kaushal:latest
