version: 0.2

phases:
  pre_build:
    commands:
      - echo Login into AWS ECR
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 618253162746.dkr.ecr.us-west-2.amazonaws.com
      - echo Installing Docker...
      - apt-get update -y
      - apt install apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      - apt-cache policy docker-ce
      - apt install docker-ce -y
      - service docker start
  build:
    commands:
      - echo Building Docker image...
      - sudo service docker start
      - sudo docker build .
  post_build:
    commands:
      - echo Pushing Docker image to ECR repository...
      - docker push 618253162746.dkr.ecr.us-west-2.amazonaws.com/kaushal:latest
